apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-jmx-exporter
  name: kafka-jmx-exporter
spec:
  selector:
    app: kafka-jmx-exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9138
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-jmx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-jmx-exporter
  template:
    metadata:
      name: kafka-jmx-exporter
      labels:
        app: kafka-jmx-exporter
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: kafka-exporter
        image: 172.22.111.199:80/cloud/kafka_jmx_exporter:1.0
        args: ["/jmx_prometheus/kafka-0-8-2.yml"]
        ports:
        - name: exporter
          containerPort: 9138
        volumeMounts:
        - mountPath: /jmx_prometheus
          name: config
      volumes:
        - name: config
          configMap:
            name: kafka-jmx-exporter-config
