apiVersion: v1
kind: Service
metadata:
  labels:
    name: pgpool-exporter
  name: pgpool-exporter
spec:
  selector:
    app: pgpool-exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgpool-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool-exporter
  template:
    metadata:
      name: pgpool-exporter
      labels:
        app: pgpool-exporter
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: pgpool-exporter
        image: 172.22.111.199:80/cloud/pgpool_exporter:1.0
        command: ['python', '/opt/pg_app/pgpool_exporter.py']
        ports:
        - name: web
          containerPort: 8000
