apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-exporter
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9187
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      name: postgres-exporter
      labels:
        app: postgres-exporter
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: postgres-exporter
        image: 172.22.111.199:80/cloud/postgres_exporter:1.0
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgres:postgres@database-pgpool-service:5432/?sslmode=disable"
        args:
          - '-log.format=logger:stdout?json=true'
          - '-extend.query-path=/opt/queries.yaml'
        ports:
        - name: web
          containerPort: 9187
        volumeMounts:
        - name: config-volume
          mountPath: /opt
      volumes:
      - name: config-volume
        configMap:
          name: pg-exporter-configmap
